-- Güneşin Sofrası Meyhane — menu_items seed
-- schema.sql'i çalıştırdıktan sonra bu dosyayı çalıştır.
-- Varsa günceller (ON CONFLICT), yoksa ekler.

INSERT INTO menu_items (restaurant_id, item_id, category, name, price, description, allergens, is_active) VALUES
-- Fix Menü
('gunesin-sofrasi','g001','Fix Menü','Limitli Alkollü Fix Menü',2250,'Kişi başı — Her 4 kişi için: 10 çeşit meze, 2 ara sıcak (Ciğer + Güneş Böreği), ana yemek (Köfte veya Asma Yaprağında Levrek), salata ve meyve. 4 kişiye 1 adet 70cl Rakı · 2 kişiye 1 adet 75cl Şarap · 1 kişiye 2 adet 50cl Bira.','{}',true),
('gunesin-sofrasi','g002','Fix Menü','Ana Yemeksiz Fix Menü',1850,'Kişi başı — Meze seçkisi, ara sıcaklar, salata ve meyve. Alkol dahil değildir.','{}',true),
-- Soğuk Mezeler
('gunesin-sofrasi','g010','Soğuk Mezeler','Beyaz Peynir',180,'Meyhane usulü beyaz peynir','{dairy}',true),
('gunesin-sofrasi','g011','Soğuk Mezeler','Atom',260,'Acılı ezme, sarımsak, ceviz','{nuts}',true),
('gunesin-sofrasi','g012','Soğuk Mezeler','Muhammara',260,'Kırmızı biber ezmesi, ceviz, zeytinyağı','{nuts}',true),
('gunesin-sofrasi','g013','Soğuk Mezeler','Köpoğlu',280,'Közlenmiş patlıcan, yoğurt, sarımsak, domates','{dairy}',true),
('gunesin-sofrasi','g014','Soğuk Mezeler','Fava',250,'Bakla ezmesi, zeytinyağı, dereotu','{}',true),
('gunesin-sofrasi','g015','Soğuk Mezeler','Şakşuka',260,'Patlıcan, domates, biber, sarımsak, zeytinyağı','{}',true),
('gunesin-sofrasi','g016','Soğuk Mezeler','Haydari',260,'Süzme yoğurt, sarımsak, nane','{dairy}',true),
('gunesin-sofrasi','g017','Soğuk Mezeler','Humus',240,'Nohut ezmesi, tahin, zeytinyağı, paprika','{sesame}',true),
-- Deniz Mezeleri
('gunesin-sofrasi','g020','Deniz Mezeleri','Levrek Marin',490,'Taze levrek marin, limon, zeytinyağı','{fish}',true),
('gunesin-sofrasi','g021','Deniz Mezeleri','Lakerda',390,'Bir dilim tuzlanmış palamut','{fish}',true),
('gunesin-sofrasi','g022','Deniz Mezeleri','Füme Uskumru',450,'Soğuk füme uskumru','{fish}',true),
('gunesin-sofrasi','g023','Deniz Mezeleri','Deniz Mahsulleri Salatası',550,'Mevsim deniz ürünleri salatası','{fish,shellfish}',true),
-- Günün Mezeleri
('gunesin-sofrasi','g030','Günün Mezeleri','Girit Ezme',290,'Girit usulü peynir ezmesi, zeytinyağı','{dairy}',true),
('gunesin-sofrasi','g031','Günün Mezeleri','Yoğurtlu Kabak Şayan',270,'Kabak, yoğurt, sarımsak, nane','{dairy}',true),
('gunesin-sofrasi','g032','Günün Mezeleri','Pilaki',240,'Fasulye veya balık pilakisi, zeytinyağı','{}',true),
('gunesin-sofrasi','g033','Günün Mezeleri','Acılı Ezme',240,'Közlenmiş biber, domates, soğan ezmesi','{}',true),
('gunesin-sofrasi','g034','Günün Mezeleri','Zahter Salatası',260,'Taze zahter otu salatası, zeytinyağı, limon','{}',true),
('gunesin-sofrasi','g035','Günün Mezeleri','Köz Patlıcan',260,'Közlenmiş patlıcan, zeytinyağı, sarımsak','{}',true),
('gunesin-sofrasi','g036','Günün Mezeleri','Enginar Kalbi',390,'Zeytinyağlı enginar kalbi','{}',true),
('gunesin-sofrasi','g037','Günün Mezeleri','Kaya Koruğu',240,'Taze kaya koruğu, zeytinyağı, limon','{}',true),
('gunesin-sofrasi','g038','Günün Mezeleri','Topik',300,'Nohut ezmeli Ermeni mezesi, soğan, çam fıstığı','{nuts}',true),
('gunesin-sofrasi','g039','Günün Mezeleri','Kuru Cacık',240,'Süzme yoğurt, sarımsak, salatalık, nane','{dairy}',true),
('gunesin-sofrasi','g040','Günün Mezeleri','Pazı Kavurma',290,'Zeytinyağlı pazı kavurma','{}',true),
('gunesin-sofrasi','g041','Günün Mezeleri','Kuru Domates Mezesi',250,'Kuru domates, zeytinyağı, baharatlar','{}',true),
('gunesin-sofrasi','g042','Günün Mezeleri','Kıska Soğan',260,'Çıtır kızartılmış soğan','{gluten}',true),
-- Ara Sıcaklar
('gunesin-sofrasi','g050','Ara Sıcaklar','Yaprak Ciğer',680,'İnce dilim kuzuciğer kavurma','{}',true),
('gunesin-sofrasi','g051','Ara Sıcaklar','Enginar Kalbi Izgara',450,'Izgara enginar kalbi, zeytinyağı','{}',true),
('gunesin-sofrasi','g052','Ara Sıcaklar','Paçanga',350,'Pastırmalı ve kaşarlı börek','{gluten,dairy}',true),
('gunesin-sofrasi','g053','Ara Sıcaklar','Kalamar Tava',690,'Çıtır kalamar tava, tartar sos','{gluten,shellfish}',true),
('gunesin-sofrasi','g054','Ara Sıcaklar','Karides Güveç',650,'Güveçte karides, domates, sarımsak, tereyağ','{shellfish,dairy}',true),
('gunesin-sofrasi','g055','Ara Sıcaklar','Kiremitte Peynirli Mantar',390,'Kiremit üstünde peynirli mantar','{dairy}',true),
('gunesin-sofrasi','g056','Ara Sıcaklar','Kalamar Izgara',720,'Izgara kalamar, zeytinyağı, limon','{shellfish}',true),
('gunesin-sofrasi','g057','Ara Sıcaklar','Dil Izgara',750,'Izgara dana dil','{}',true),
('gunesin-sofrasi','g058','Ara Sıcaklar','Sıcak Ot',330,'Mevsim otları sıcak meze','{}',true),
('gunesin-sofrasi','g059','Ara Sıcaklar','Tereyağlı Karides',680,'Tereyağlı sote karides','{shellfish,dairy}',true),
('gunesin-sofrasi','g060','Ara Sıcaklar','Pastırmalı Humus',480,'Sıcak humus, pastırma, tereyağ','{sesame}',true),
('gunesin-sofrasi','g061','Ara Sıcaklar','Güneş Böreği',320,'Güneşin Sofrası''na özel börek','{gluten,dairy}',true),
('gunesin-sofrasi','g062','Ara Sıcaklar','Biralı Çıtır Kabak',390,'Bira hamurunda kabak kızartması','{gluten}',true),
('gunesin-sofrasi','g063','Ara Sıcaklar','Ahtapot Izgara',1350,'Izgara ahtapot, zeytinyağı, limon, kekik','{shellfish}',true),
('gunesin-sofrasi','g064','Ara Sıcaklar','Balık Kokoreç',620,'Balık iç organlarıyla hazırlanan kokoreç','{gluten}',true),
('gunesin-sofrasi','g065','Ara Sıcaklar','Balık Köftesi',650,'2 adet balık köftesi','{gluten,fish,eggs}',true),
('gunesin-sofrasi','g066','Ara Sıcaklar','Kuzu Kokoreç',650,'Geleneksel kuzu kokoreç','{gluten}',true),
('gunesin-sofrasi','g067','Ara Sıcaklar','Patlıcan Kumpir',475,'Mevsiminde — Patlıcan kumpir','{dairy}',true),
-- Ana Yemekler (Deniz)
('gunesin-sofrasi','g070','Ana Yemekler (Deniz)','Asma Yaprağında Levrek',950,'Taze levrek, asma yaprağında pişmiş','{fish}',true),
('gunesin-sofrasi','g071','Ana Yemekler (Deniz)','Güveçte Balık Kavurma',850,'Güveçte taze balık kavurma','{fish}',true),
('gunesin-sofrasi','g072','Ana Yemekler (Deniz)','Çupra Izgara',850,'Taze çupra ızgara','{fish}',true),
('gunesin-sofrasi','g073','Ana Yemekler (Deniz)','Levrek Izgara',850,'Taze levrek ızgara','{fish}',true),
('gunesin-sofrasi','g074','Ana Yemekler (Deniz)','Mevsim Balıkları',0,'Günlük fiyat için lütfen garson ile görüşünüz','{fish}',true),
-- Ana Yemekler (Et)
('gunesin-sofrasi','g080','Ana Yemekler (Et)','Güveçte Çoban Kavurma',980,'180 gr antrikot, güveçte çoban kavurma','{}',true),
('gunesin-sofrasi','g081','Ana Yemekler (Et)','Köfte',700,'180 gr ızgara köfte','{gluten}',true),
('gunesin-sofrasi','g082','Ana Yemekler (Et)','Kuzu Pirzola',1250,'250 gr kuzu pirzola ızgara','{}',true),
('gunesin-sofrasi','g083','Ana Yemekler (Et)','Karışık Izgara',1700,'360 gr — 2 köfte + 2 kalem pirzola + 2 kuzu şiş','{gluten}',true),
-- Salatalar
('gunesin-sofrasi','g090','Salatalar','Yeşil Salata (Orta)',250,'Taze yeşil salata — Orta boy','{}',true),
('gunesin-sofrasi','g091','Salatalar','Yeşil Salata (Büyük)',300,'Taze yeşil salata — Büyük boy','{}',true),
('gunesin-sofrasi','g092','Salatalar','Roka Salata (Orta)',280,'Roka, zeytinyağı, limon — Orta boy','{}',true),
('gunesin-sofrasi','g093','Salatalar','Roka Salata (Büyük)',340,'Roka, zeytinyağı, limon — Büyük boy','{}',true),
('gunesin-sofrasi','g094','Salatalar','P. Roka Salatası (Orta)',325,'Parmesan rokası — Orta boy','{dairy}',true),
('gunesin-sofrasi','g095','Salatalar','P. Roka Salatası (Büyük)',380,'Parmesan rokası — Büyük boy','{dairy}',true),
('gunesin-sofrasi','g096','Salatalar','Çoban Salatası (Orta)',300,'Domates, salatalık, soğan, maydanoz — Orta boy','{}',true),
('gunesin-sofrasi','g097','Salatalar','Çoban Salatası (Büyük)',360,'Domates, salatalık, soğan, maydanoz — Büyük boy','{}',true),
('gunesin-sofrasi','g098','Salatalar','Gavurdağı Salatası (Orta)',350,'Domates, biber, ceviz, nar ekşisi — Orta boy','{nuts}',true),
('gunesin-sofrasi','g099','Salatalar','Gavurdağı Salatası (Büyük)',420,'Domates, biber, ceviz, nar ekşisi — Büyük boy','{nuts}',true),
('gunesin-sofrasi','g100','Salatalar','İstanbul Salatası (Orta)',300,'Mevsim yeşillikleri — Orta boy','{}',true),
('gunesin-sofrasi','g101','Salatalar','İstanbul Salatası (Büyük)',350,'Mevsim yeşillikleri — Büyük boy','{}',true),
-- Tatlı & Meyve
('gunesin-sofrasi','g110','Tatlı & Meyve','Fırında Portakallı Helva',330,'Portakal aromalı fırın helvası','{nuts,gluten}',true),
('gunesin-sofrasi','g111','Tatlı & Meyve','Dondurmalı İrmik Helvası',375,'İrmik helvası, dondurma ile servis','{dairy,nuts,gluten}',true),
('gunesin-sofrasi','g112','Tatlı & Meyve','Antakya Kabak Tatlısı',375,'Geleneksel kabak tatlısı, kaymak ile','{dairy,nuts}',true),
('gunesin-sofrasi','g113','Tatlı & Meyve','Meyve Tabağı',310,'2 kişilik mevsim meyveleri tabağı','{}',true),
-- Rakı
('gunesin-sofrasi','g120','Rakı','Yeni Rakı',300,'Tek 300₺ · Duble 450₺ · 20cl 950₺ · 35cl 1.470₺ · 50cl 1.950₺ · 70cl 2.500₺ · 100cl 3.300₺','{}',true),
('gunesin-sofrasi','g121','Rakı','Yeni Seri',1050,'20cl 1.050₺ · 35cl 1.690₺ · 50cl 2.200₺ · 70cl 2.750₺ · 100cl 3.650₺','{}',true),
('gunesin-sofrasi','g122','Rakı','Alâ',2050,'35cl 2.050₺ · 70cl 3.600₺','{}',true),
('gunesin-sofrasi','g123','Rakı','Tekirdağ',1550,'35cl 1.550₺ · 50cl 2.100₺ · 70cl 2.650₺ · 100cl 3.600₺','{}',true),
('gunesin-sofrasi','g124','Rakı','Altın Seri',1200,'20cl 1.200₺ · 35cl 1.800₺ · 50cl 2.450₺ · 70cl 3.100₺ · 100cl 3.950₺','{}',true),
('gunesin-sofrasi','g125','Rakı','Rezerv',2100,'35cl 2.100₺ · 70cl 3.650₺','{}',true),
('gunesin-sofrasi','g126','Rakı','Göbek',1350,'20cl 1.350₺ · 35cl 2.150₺ · 50cl 3.000₺ · 70cl 3.800₺ · 100cl 4.700₺','{}',true),
('gunesin-sofrasi','g127','Rakı','Efe Rakı (Yeşil)',1090,'20cl 1.090₺ · 35cl 1.650₺ · 50cl 2.250₺ · 70cl 2.850₺ · 100cl 3.700₺','{}',true),
('gunesin-sofrasi','g128','Rakı','Efe Gold',1250,'20cl 1.250₺ · 35cl 1.850₺ · 50cl 2.550₺ · 70cl 3.200₺ · 100cl 4.000₺','{}',true),
('gunesin-sofrasi','g129','Rakı','Efe Göbek',1290,'20cl 1.290₺ · 35cl 2.150₺ · 50cl 2.980₺ · 70cl 3.750₺ · 100cl 5.100₺','{}',true),
('gunesin-sofrasi','g130','Rakı','Sarı Zeybek 3 Meşe',1350,'20cl 1.350₺ · 35cl 2.350₺ · 50cl 2.950₺ · 70cl 3.800₺ · 100cl 5.200₺','{}',true),
('gunesin-sofrasi','g131','Rakı','Beylerbeyi Göbek',2250,'35cl 2.250₺ · 70cl 4.100₺','{}',true),
('gunesin-sofrasi','g132','Rakı','Kulüp',1950,'35cl 1.950₺ · 70cl 3.250₺','{}',true),
('gunesin-sofrasi','g133','Rakı','Kulüp Delux',1900,'35cl 1.900₺ · 70cl 3.150₺','{}',true),
('gunesin-sofrasi','g134','Rakı','Yeni Rakı Giz',6300,'50cl 6.300₺','{}',true),
('gunesin-sofrasi','g135','Rakı','Yeni Rakı Pus',5500,'50cl 5.500₺','{}',true),
-- Şarap Kırmızı
('gunesin-sofrasi','g140','Şarap (Kırmızı)','Turasan Libra',1650,'Kırmızı şarap — 75cl','{}',true),
('gunesin-sofrasi','g141','Şarap (Kırmızı)','T. Cab. Sauvignon',1850,'Turasan Cabernet Sauvignon — 75cl','{}',true),
('gunesin-sofrasi','g142','Şarap (Kırmızı)','Turasan Merlot',1850,'75cl','{}',true),
('gunesin-sofrasi','g143','Şarap (Kırmızı)','T. Seneler Ökg-Bğz',2800,'Turasan Seneler Öküzgözü-Boğazkere — 75cl','{}',true),
('gunesin-sofrasi','g144','Şarap (Kırmızı)','Terra Ökg-Bğz',1600,'Terra Öküzgözü-Boğazkere — 75cl','{}',true),
('gunesin-sofrasi','g145','Şarap (Kırmızı)','Terra Shiraz',1600,'75cl','{}',true),
('gunesin-sofrasi','g146','Şarap (Kırmızı)','Kayra Vintage Ökg',2900,'Kayra Vintage Öküzgözü — 75cl','{}',true),
-- Şarap Beyaz
('gunesin-sofrasi','g150','Şarap (Beyaz)','Turasan Libra Beyaz',1650,'75cl','{}',true),
('gunesin-sofrasi','g151','Şarap (Beyaz)','Turasan Narince',1850,'75cl','{}',true),
('gunesin-sofrasi','g152','Şarap (Beyaz)','Turasan Emir',1850,'75cl','{}',true),
('gunesin-sofrasi','g153','Şarap (Beyaz)','T. Seneler Char.',2800,'Turasan Seneler Chardonnay — 75cl','{}',true),
('gunesin-sofrasi','g154','Şarap (Beyaz)','Leona Nar-Cha.',1650,'Leona Narince-Chardonnay — 75cl','{}',true),
('gunesin-sofrasi','g155','Şarap (Beyaz)','Terra Narince',1650,'75cl','{}',true),
('gunesin-sofrasi','g156','Şarap (Beyaz)','K. Vintage Narince',2900,'Kayra Vintage Narince — 75cl','{}',true),
-- Şarap Rosé
('gunesin-sofrasi','g160','Şarap (Rosé)','Leona Blush',1650,'Rosé — 75cl','{}',true),
('gunesin-sofrasi','g161','Şarap (Rosé)','Kadeh Şarap',390,'Günün şarabı — kadeh','{}',true),
('gunesin-sofrasi','g162','Şarap (Rosé)','Kadeh Rosé',390,'Günün roséi — kadeh','{}',true),
('gunesin-sofrasi','g163','Şarap (Rosé)','Şişe Bira',290,'50cl şişe bira','{gluten}',true),
-- İçecekler
('gunesin-sofrasi','g170','İçecekler','Büyük Su',90,'Büyük boy kaynak suyu','{}',true),
('gunesin-sofrasi','g171','İçecekler','Soda',110,'Maden suyu / soda','{}',true),
('gunesin-sofrasi','g172','İçecekler','Churchill',140,'Soğuk Churchill','{}',true),
('gunesin-sofrasi','g173','İçecekler','Uludağ Gazoz',160,'Klasik Uludağ gazoz','{}',true),
('gunesin-sofrasi','g174','İçecekler','Ice Tea',160,'Limon veya şeftali','{}',true),
('gunesin-sofrasi','g175','İçecekler','Büyük Şalgam',180,'Büyük boy şalgam suyu','{}',true),
('gunesin-sofrasi','g176','İçecekler','Küçük Şalgam',100,'Küçük boy şalgam suyu','{}',true),
('gunesin-sofrasi','g177','İçecekler','Türk Kahvesi',120,'Geleneksel Türk kahvesi','{}',true)
ON CONFLICT (restaurant_id, item_id) DO UPDATE
  SET name        = EXCLUDED.name,
      price       = EXCLUDED.price,
      description = EXCLUDED.description,
      allergens   = EXCLUDED.allergens,
      is_active   = EXCLUDED.is_active,
      updated_at  = now();
